from dotenv import load_dotenv
load_dotenv()## Load all the environment variables from a .env file
import os
import streamlit as st
import sqlite3
import google.generativeai as genai
##cinfigure the api key
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

## (sql query being generated by llm model)Function to load google gemini model and provide query as response
def get_gemini_response(question,prompt):
    model = genai.GenerativeModel('gemini-2.5-flash')
    response= model.generate_content([prompt[0], question]) 
    return response.text


## Funtion to retrieve query from the sql database
def read_sql_query(sql,db):
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    cur.execute(sql)
    rows = cur.fetchall()
    conn.commit()
    conn.close()
    for row in rows:
        print(row)
    return rows

## define your prompt
prompt = [""" You are an expert in converting English questions to SQL query !
The SQL database has the name student and has the following columns - NAME,CLASS,SECTION
and MARKS\n \n For example, \n Example 1 - How many entries of records are present?,
the sql command will be something like this SELECT COUNT(*) FROM STUDENT;
\n Example 2 - Tell me all the students studying in Data Science class?,
the sql command will be something like this SELECT * FROM STUDENT WHERE CLASS='Data Science';
also the sql code should not have''' in beginning or end and sql word in output"""  ]



## Streamlit app 
st.set_page_config(page_title="I can Retrieve any sql query")
st.header("Gemini App to Retrieve SQL Data")
question= st.text_input("Input:", key="input")
submit= st.button("Ask the question")

## if submit button is pressed
if submit:
    response = get_gemini_response(question,prompt)
    print(response)
    data = read_sql_query(response,"student.db")
    st.subheader("The response is:")
    for row in data:
        print(row)
        st.header(row)